// <auto-generated />
using System;
using CurriculumVitaeApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CurriculumVitaeApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251212181047_Crear-Conocimientos")]
    partial class CrearConocimientos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CurriculumVitaeApp.Models.Conocimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Conocimientos");
                });

            modelBuilder.Entity("CurriculumVitaeApp.Models.Curriculum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Curriculum");
                });

            modelBuilder.Entity("CurriculumVitaeApp.Models.CurriculumSeleccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurriculumID")
                        .HasColumnType("int");

                    b.Property<string>("TipoDato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDatoID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CurriculumSeleccion");
                });

            modelBuilder.Entity("CurriculumVitaeApp.Models.DatosBasicos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("CurriculumVitaeApp.Models.ExperienciaLaboral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaTermino")
                        .HasColumnType("date");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioID");

                    b.ToTable("AntecedentesLaborales");
                });

            modelBuilder.Entity("CurriculumVitaeApp.Models.FormacionAcademica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnhoInicio")
                        .HasColumnType("int");

                    b.Property<int?>("AnhoTermino")
                        .HasColumnType("int");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreInstitucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoInstitucionID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("TipoInstitucionID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("FormacionAcademica");
                });

            modelBuilder.Entity("CurriculumVitaeApp.Models.Habilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("CurriculumVitaeApp.Models.TipoInstitucion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("tipoInstitucion");
                });

            modelBuilder.Entity("CurriculumVitaeApp.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CurriculumVitaeApp.Models.Conocimiento", b =>
                {
                    b.HasOne("CurriculumVitaeApp.Models.Usuario", "Usuarios")
                        .WithMany("Conocimientos")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CurriculumVitaeApp.Models.DatosBasicos", b =>
                {
                    b.HasOne("CurriculumVitaeApp.Models.Usuario", "Usuarios")
                        .WithMany("DatosBasicos")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CurriculumVitaeApp.Models.ExperienciaLaboral", b =>
                {
                    b.HasOne("CurriculumVitaeApp.Models.Usuario", "Usuarios")
                        .WithMany("ExperienciaLaboral")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CurriculumVitaeApp.Models.FormacionAcademica", b =>
                {
                    b.HasOne("CurriculumVitaeApp.Models.TipoInstitucion", "TipoInstitucion")
                        .WithMany("FormacionAcademica")
                        .HasForeignKey("TipoInstitucionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CurriculumVitaeApp.Models.Usuario", "Usuarios")
                        .WithMany("FormacionAcademica")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoInstitucion");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CurriculumVitaeApp.Models.Habilidad", b =>
                {
                    b.HasOne("CurriculumVitaeApp.Models.Usuario", "Usuarios")
                        .WithMany("Habilidades")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CurriculumVitaeApp.Models.TipoInstitucion", b =>
                {
                    b.Navigation("FormacionAcademica");
                });

            modelBuilder.Entity("CurriculumVitaeApp.Models.Usuario", b =>
                {
                    b.Navigation("Conocimientos");

                    b.Navigation("DatosBasicos");

                    b.Navigation("ExperienciaLaboral");

                    b.Navigation("FormacionAcademica");

                    b.Navigation("Habilidades");
                });
#pragma warning restore 612, 618
        }
    }
}
